import AppKit
import CryptoKit

/// Content kinds that sync across a LocalCast session.
enum ClipboardContentKind: String, Codable {
    case text
    case image
    case files
}

/// Wire payload for `PacketType.clipboardUpdate`, sent by either side when its
/// pasteboard changes. Inline content and the bulk offer are mutually
/// exclusive: small text and images travel in the packet itself; files and
/// large payloads set `bulk` and move over the TCP channel.
struct ClipboardUpdatePayload: Codable {
    let updateId: UUID
    let kind: ClipboardContentKind
    let text: String?
    let rtf: Data?
    let png: Data?
    let bulk: ClipboardBulkOffer?
    /// SHA-256 of the canonical content, so the receiver can skip an apply
    /// that would recreate what its pasteboard already holds.
    let digest: Data
}

/// Announces content too large for the inline path. The receiver fetches it
/// over TCP by presenting the token.
struct ClipboardBulkOffer: Codable {
    let token: Data
    let totalBytes: Int64
    let files: [ClipboardFileStub]?
}

struct ClipboardFileStub: Codable {
    let name: String
    let size: Int64
}

/// An immutable capture of the local pasteboard, taken on the main thread.
struct ClipboardSnapshot {
    let kind: ClipboardContentKind
    let text: String?
    let rtf: Data?
    let png: Data?
    let fileURLs: [URL]
    let digest: Data

    /// Total bytes the bulk channel would move for this snapshot.
    var totalContentBytes: Int64 {
        switch kind {
        case .files:
            return fileURLs.reduce(Int64(0)) { $0 + (fileSize($1) ?? 0) }
        case .image:
            return Int64(png?.count ?? 0)
        case .text:
            return Int64((text?.utf8.count ?? 0) + (rtf?.count ?? 0))
        }
    }

    var fileStubs: [ClipboardFileStub] {
        fileURLs.map { ClipboardFileStub(name: $0.lastPathComponent, size: fileSize($0) ?? 0) }
    }

    private func fileSize(_ url: URL) -> Int64? {
        (try? url.resourceValues(forKeys: [.fileSizeKey]))?.fileSize.map(Int64.init)
    }
}

/// Pasteboard capture and apply. All entry points must run on the main thread;
/// NSPasteboard is not safe from arbitrary queues.
enum ClipboardPasteboard {
    /// Password managers mark copies with these types (nspasteboard.org
    /// conventions) so clipboard utilities leave them alone. Transient covers
    /// auto-generated ephemera as well.
    private static let excludedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    /// Capture the pasteboard's current content, or nil when it is empty,
    /// marked confidential, or holds nothing we sync. Priority is files, then
    /// image, then text: Finder puts both file URLs and a name string on the
    /// pasteboard, and the files must win.
    static func capture(from pasteboard: NSPasteboard) -> ClipboardSnapshot? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: excludedTypes.contains) else { return nil }

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            // Regular files only in v1; directories are skipped.
            let regular = urls.filter { url in
                (try? url.resourceValues(forKeys: [.isRegularFileKey]))?.isRegularFile == true
            }
            if !regular.isEmpty {
                return ClipboardSnapshot(
                    kind: .files, text: nil, rtf: nil, png: nil,
                    fileURLs: regular, digest: filesDigest(regular)
                )
            }
        }

        if let png = pasteboard.data(forType: .png) ?? pngFromTIFF(pasteboard.data(forType: .tiff)) {
            return ClipboardSnapshot(
                kind: .image, text: nil, rtf: nil, png: png,
                fileURLs: [], digest: digest(kind: .image, chunks: [png])
            )
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let rtf = pasteboard.data(forType: .rtf)
            return ClipboardSnapshot(
                kind: .text, text: text, rtf: rtf, png: nil,
                fileURLs: [], digest: digest(kind: .text, chunks: [Data(text.utf8), rtf ?? Data()])
            )
        }

        return nil
    }

    /// Write remote text or image content to the pasteboard. Returns the
    /// change count from `clearContents()`, which the caller records for echo
    /// suppression; a read-back after the writes would race a concurrent user
    /// copy and could swallow it.
    @discardableResult
    static func applyInline(kind: ClipboardContentKind, text: String?, rtf: Data?, png: Data?, to pasteboard: NSPasteboard) -> Int {
        let changeCount = pasteboard.clearContents()
        switch kind {
        case .text:
            if let text { pasteboard.setString(text, forType: .string) }
            if let rtf { pasteboard.setData(rtf, forType: .rtf) }
        case .image:
            if let png {
                pasteboard.setData(png, forType: .png)
                // Older apps read only TIFF; write both representations.
                if let tiff = NSImage(data: png)?.tiffRepresentation {
                    pasteboard.setData(tiff, forType: .tiff)
                }
            }
        case .files:
            break
        }
        return changeCount
    }

    /// Put file promise providers on the pasteboard. Returns the change count
    /// from `clearContents()`.
    @discardableResult
    static func applyPromises(_ providers: [NSFilePromiseProvider], to pasteboard: NSPasteboard) -> Int {
        let changeCount = pasteboard.clearContents()
        pasteboard.writeObjects(providers)
        return changeCount
    }

    /// Digest for text and image content: kind tag plus content bytes.
    static func digest(kind: ClipboardContentKind, chunks: [Data]) -> Data {
        var hasher = SHA256()
        hasher.update(data: Data(kind.rawValue.utf8))
        for chunk in chunks { hasher.update(data: chunk) }
        return Data(hasher.finalize())
    }

    /// Digest for file content, over sorted name:size pairs. Content bytes are
    /// deliberately excluded: hashing a 100 MB copy on every poll tick is not
    /// acceptable, and echo suppression for files leans on the change count.
    static func filesDigest(_ urls: [URL]) -> Data {
        let entries = urls
            .map { url -> String in
                let size = (try? url.resourceValues(forKeys: [.fileSizeKey]))?.fileSize ?? 0
                return "\(url.lastPathComponent):\(size)"
            }
            .sorted()
            .joined(separator: "|")
        return digest(kind: .files, chunks: [Data(entries.utf8)])
    }

    private static func pngFromTIFF(_ tiff: Data?) -> Data? {
        guard let tiff, let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
